import Link from "next/link"
import "./globals.css"
import Image from "next/image"

//import font awesome
import "@fortawesome/fontawesome-svg-core/styles.css"



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body>
        {/*Area Header*/}
        <header>
        {/*area image/banner*/}
        {/* <img src="../images/logo.png" alt="Logo UTI" /> */}
        <Image src={"/images/logo.png"} alt="Logo UTI" width={320} height={60}></Image>
        {/*area menu*/}
        <nav className="text-center mt-5 flex justify-center">
          <Link href={"/"} className="bg-green-500 hover:bg-green-700 text-white rounded-full px-5 py-2.5 mr-3">Data Mahasiswa</Link> 
          <Link href={"/"} className="bg-green-500 hover:bg-green-700 text-white rounded-full px-5 py-2.5 ml-3">Log Data Mahasiswa</Link>
        </nav>
        </header>
        {/*area content*/}
        <section className="m-5">
        {children}
        </section>
        {/*area footer*/}
        <footer className="flex justify-center bg-blue-500 text-white mt-5 py-5">
          Copyright &copy; 2024-Dimas
        </footer>
      </body>
    </html>
  )
}
